### ISSUE TITLE
Relative modules not found

### ISSUE THREAD

**Issue by activemonkeys** [zuramai/nuxewind#1]
Thanks for providing this nice admin template. When running this script out-of-the-box, the following errors occur: 

 ERROR  Failed to compile with 2 errors                                                                       
These relative modules were not found:                                                             
                                                                                                              f
* ./fonts/bootstrap-icons.woff2?5813790c1ebd573b51a03ec84367082a in ./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/scss/icons.scss
* ./fonts/bootstrap-icons.woff?5813790c1ebd573b51a03ec84367082a in ./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./assets/scss/icons.scss

**Comment by zuramai** [comment]
Solved. I've moved the node_modules/bootstrap-icons file to local assets
